### ISSUE TITLE
Database schema missing "Name" column

### ISSUE THREAD

**Issue by atomtay** [MAPC/zoning-atlas-api#1]
In the frontend Edits form, there is a required field for "Name." However, that field is missing from the receiving database table.

**Comment by atomtay** [comment]
@mzagaja I just noticed this when checking to see if there were any new submissions this morning---so far the only ones to come in via the form are our prior tests + a few entries from Tim. This would just be a minor Rails migration and re-deploy, right?

**Comment by mzagaja** [comment]
Yeah you also just need to add the field to the controller. Feel free to give it a shot in a PR and I can review after staff meeting.
